name: Index Helm Charts (Manually)

on:
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Download Released Chart
        run: gh release download --pattern '*.tgz' --repo p-le/devops-todoapp-helm-chart
